### ISSUE TITLE
PingFang SC

### ISSUE THREAD

**Issue by BlackGear** [zenozeng/fonts.css#26]
For new iOS and OS X.

**Comment by zenozeng** [comment]
你方便执行一下 fc-list 命令吗，我这里没有设备。

Daniel.Zeng <notifications@github.com>于2015年6月9日周二 22:03写道：

**Comment by zenozeng** [comment]
font family 就叫 PingFang SC 是吗？

**Comment by BlackGear** [comment]
see this : http://bitinn.net/11280/

目前beta版里名字前面被加入了"."，使得字体默认被隐藏起来，目测时机成熟后点号会被去掉…

**Comment by zenozeng** [comment]
Thanks.
