### ISSUE TITLE
Now San Francisco is the default font for Apple

### ISSUE THREAD

**Issue by yzyzsun** [zenozeng/fonts.css#29]
But SF is still a hidden font in OS X El Capitan, we cannot specify it directly. Instead, `-apple-system` works. Ref: http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/

**Comment by zenozeng** [comment]
我想再等等。基于这种 hack 实现的感觉可以晚点再说。

**Comment by yzyzsun** [comment]
苹果正在向 W3C 提议将 `-apple-system` 纳入标准，目前似乎还没定论。Ref: https://lists.w3.org/Archives/Public/www-style/2015Jul/0169.html

**Comment by zenozeng** [comment]
- https://www.webkit.org/blog/3709/using-the-system-font-in-web-content/
- http://www.w3.org/TR/css3-fonts/#font-prop

**Comment by zenozeng** [comment]
Added, thanks.
