### ISSUE TITLE
Kai family not working properly on Windows

### ISSUE THREAD

**Issue by jkwchk** [zenozeng/fonts.css#32]
The Kai family is not working properly on my Windows 10 which has Traditional Chinese support files installed only, and I believe the GB or Simplified Chinese edition of KaiTi font will be installed only if SC support was added.

So I was wondering if you could add DFKai-SB to the list. DFKai-SB(https://zh.wikipedia.org/wiki/%E6%A8%99%E6%A5%B7%E9%AB%94) is a TC version of Kaiti font and support both TC and SC.

**Comment by zenozeng** [comment]
@jkwchk Thanks for your feedback! DFKai-SB should be available in fonts.css@1.5.0.
