### ISSUE TITLE
The repository problem in npm

### ISSUE THREAD

**Issue by nolsherry** [zenozeng/fonts.css#33]
Hi @zenozeng , 
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project,
and we want to host this library, 
I have some problems,
I downloaded the library from npm, 
but I found that there are only two versions (`v1.3.1` , `v1.4.0`) in [npm](https://www.npmjs.com/package/fonts.css).
However there are 5 versions in [github](https://github.com/zenozeng/fonts.css).
Can you help me add the missing repositories (`v1.0.0` , `v1.1.0`, `v1.3.0`)? Thanks!

cdnjs/cdnjs#9171

**Comment by zenozeng** [comment]
@nolsherry Sorry for my late response. v1.0.0, v1.1.0 and v1.3.0 now should be on npm.

**Comment by nolsherry** [comment]
@zenozeng, thanks for your help!
