### ISSUE TITLE
移动端中文字体问题，移动端中文字体能用的只有 “无衬字 (sans-serif)” 吧 

### ISSUE THREAD

**Issue by Akimyou** [zenozeng/fonts.css#38]
几种默认的 font-family 回退

font-family: cursive;
font-family: fantasy;
font-family: monospace;
font-family: sans-serif;
font-family: serif;

在桌面端中英文字体都有效，在移动端英文字体都有效，但中文字体能用的只有 无衬字 (sans-serif)。

是否有除了 web-font 之外的解决方案？

**Comment by Jay-G2017** [comment]
iphone safari下楷体, 宋体, 仿宋都不能显示
